version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true